os: linux
dist: bionic
language: c

jobs:
  include:
    env:
    - MATRIX_EVAL="CC=gcc" CF=-DBUILD_SHARED_LIBS=OFF ARCH="x86_64" DEPLOY="true"
    - MATRIX_EVAL="CC='gcc -m32'" CF="-DBUILD_SHARED_LIBS=OFF -DCMAKE_LIBRARY_PATH=/usr/lib32"
      PACKAGES="gcc-multilib lib32z1-dev" ARCH="i686" DEPLOY="true"
    - MATRIX_EVAL="CC=gcc" CF="-DBUILD_SHARED_LIBS=ON" ARCH="x86_64"
      DEPLOY="false"

before_install:
- sudo apt-get install -y rpm
- git clone https://github.com/huskyproject/huskylib ~/build/huskyproject/huskylib
- git clone https://github.com/huskyproject/smapi ~/build/huskyproject/smapi
- git clone https://github.com/huskyproject/fidoconf ~/build/huskyproject/fidoconf
- git clone https://github.com/huskyproject/hptzip ~/build/huskyproject/hptzip
- git clone https://github.com/huskyproject/areafix ~/build/huskyproject/areafix
- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends
  --no-upgrade -qq $PACKAGES; fi
- wget -q -O - https://files.viva64.com/etc/pubkey.txt | sudo apt-key add -
- sudo wget -O /etc/apt/sources.list.d/viva64.list https://files.viva64.com/etc/viva64.list
- sudo apt-get update; sudo apt-get install -y pvs-studio

script:
- if [[ "$TRAVIS_BRANCH" != "TRAVIS_TAG" && "$TRAVIS_BRANCH" != "master" ]]; then MY_BRANCH="$TRAVIS_BRANCH"; fi
- eval "${MATRIX_EVAL}"
- cd  ~/build/huskyproject/huskylib
- if [[ -n "$MY_BRANCH" ]]; then MY_BRANCH=$(git branch --list "$MY_BRANCH"); [[ -n "$MY_BRANCH" ]] && MY_BRANCH=${MY_BRANCH:2}; fi
- if [[ -n "$MY_BRANCH" ]]; then git checkout "$MY_BRANCH"; fi
- mkdir build
- cd build
- cmake .. ${CF}
- cmake --build .
- sudo make install
- cd  ~/build/huskyproject/smapi
- if [[ -n "$MY_BRANCH" ]]; then MY_BRANCH=$(git branch --list "$MY_BRANCH"); [[ -n "$MY_BRANCH" ]] && MY_BRANCH=${MY_BRANCH:2}; fi
- if [[ -n "$MY_BRANCH" ]]; then git checkout "$MY_BRANCH"; fi
- mkdir build
- cd build
- cmake .. ${CF}
- cmake --build .
- sudo make install
- cd  ~/build/huskyproject/fidoconf
- if [[ -n "$MY_BRANCH" ]]; then MY_BRANCH=$(git branch --list "$MY_BRANCH"); [[ -n "$MY_BRANCH" ]] && MY_BRANCH=${MY_BRANCH:2}; fi
- if [[ -n "$MY_BRANCH" ]]; then git checkout "$MY_BRANCH"; fi
- mkdir build
- cd build
- cmake .. ${CF}
- cmake --build .
- sudo make install
- cd  ~/build/huskyproject/areafix
- if [[ -n "$MY_BRANCH" ]]; then MY_BRANCH=$(git branch --list "$MY_BRANCH"); [[ -n "$MY_BRANCH" ]] && MY_BRANCH=${MY_BRANCH:2}; fi
- if [[ -n "$MY_BRANCH" ]]; then git checkout "$MY_BRANCH"; fi
- mkdir build
- cd build
- cmake .. ${CF}
- cmake --build .
- sudo make install
- cd  ~/build/huskyproject/hptzip
- if [[ -n "$MY_BRANCH" ]]; then MY_BRANCH=$(git branch --list "$MY_BRANCH"); [[ -n "$MY_BRANCH" ]] && MY_BRANCH=${MY_BRANCH:2}; fi
- if [[ -n "$MY_BRANCH" ]]; then git checkout "$MY_BRANCH"; fi
- mkdir build
- cd build
- cmake .. ${CF}
- cmake --build .
- sudo make install
- cd $TRAVIS_BUILD_DIR
- if [[ -n "$PVS_USERNAME" ]]; then pvs-studio-analyzer credentials -o $TRAVIS_BUILD_DIR/PVS-Studio.lic $PVS_USERNAME $PVS_KEY; fi
- if [[ -n "$PVS_USERNAME" ]]; then cmake . -Bbuild "${CF}" -DCMAKE_EXPORT_COMPILE_COMMANDS=On -DCPACK_DEBIAN_PACKAGE_MAINTAINER=travis-ci; fi
- if [[ -z "$PVS_USERNAME" ]]; then cmake . -Bbuild "${CF}" -DCPACK_DEBIAN_PACKAGE_MAINTAINER=travis-ci; fi
- if [[ -n "$PVS_USERNAME" ]]; then pvs-studio-analyzer trace -- cmake --build build; else cmake --build build; fi
- if [[ -n "$PVS_USERNAME" ]]; then pvs-studio-analyzer analyze -l $TRAVIS_BUILD_DIR/PVS-Studio.lic -s $TRAVIS_BUILD_DIR/suppress_base.json -o build/pvs.log; fi
- if [[ -n "$PVS_USERNAME" ]]; then plog-converter -a 'GA:1,2;64:1,2;OP:1,2' -t tasklist -o build/pvs.tasks build/pvs.log; fi
- if [[ -n "$PVS_USERNAME" ]]; then cat build/pvs.tasks; fi
- if [[ -n "$PVS_USERNAME" ]]; then ! grep -vP '\serr\s+Help:' build/pvs.tasks | grep -P '\serr\s'; fi
- cd build
- cpack
- cpack -G RPM
- cpack -G DEB
- for file in *.rpm; do mv $file $(basename $file .rpm).${ARCH}.rpm; done
- for file in *.deb; do mv $file $(basename $file .deb).${ARCH}.deb; done
- for file in *.tar.gz; do mv $file $(basename $file .tar.gz).${ARCH}.tar.gz; done

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  skip_cleanup: true
  file: 
    - $TRAVIS_BUILD_DIR/build/*.rpm
    - $TRAVIS_BUILD_DIR/build/*.deb
    - $TRAVIS_BUILD_DIR/build/*.tar.gz
  on:
    tags: true
    branch: master
    condition: $DEPLOY="true"
